### ISSUE TITLE
If...

### ISSUE THREAD

**Issue by Leeless1** [codinggrace/text_based_adventure_game#1]
if __name__ == '__main__':
       main()

What does this actually do?

I have tried removing it from the code, and things go awry.  But I also tried replacing it with just:

main()

and things run no different.

**Comment by whykay** [comment]
Are you running a Python script or are you running code in the Python interpreter (command line)?

Example code below would be something you find in a Python script file, say I named my file with the code in it called `myfirstpython.py`

``` python
def somefunction():
    print("running this first")

if __name__ == "__main__":
    somefunction()
    print("hello, just ran a function")  
```

When you run the script, Python loads all the code from top to bottom and if no `if __name__ == "__main__":` is found, it will execute all the code from first to the last line.

If it finds `if __name__ == "__main__":`, it will execute the code from that point onwards (line 4 in our example). 

With the sample code saved in a file, in a terminal,  type
```python myfirstpython.py```

It will call `somefunction()` first before printing the next string "hello, just ran a function".

Here is the output when I ran it in my terminal
```
running this first
hello, just ran a function
```

NOTE: There's a double underscore before and after `name` and `main`, that is important. 

You can reference more via https://realpython.com/python-main-function/

**Comment by whykay** [comment]
And I forgot, if you are running code and testing it out in your Python interpreter, you don't need to use `if __name__ == "__main__":`

Ref: https://realpython.com/lessons/running-python-code-interactively/

**Comment by Leeless1** [comment]
Ah, awesome. That's clear, and good to know.

I am running it in Google.collab, so that must be why I noticed no effect then. Thank you.

**Comment by whykay** [comment]
Great stuff, I'll close this issue.
